### ISSUE TITLE
error when trying to convert.

### ISSUE THREAD

**Issue by mihai-morman** [olety/epwing2kindle#4]
`Processing files:   0%|                                                                        | 0/30 [00:00<?, ?file/s]
Traceback (most recent call last):
  File "yomi2tab.py", line 229, in <module>
    result = process_folder(args.folder, simplify=args.simplify)
  File "yomi2tab.py", line 127, in process_folder
    'unknown3', 'def', 'id', 'unknown4']
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 3094, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/src/properties.pyx", line 65, in pandas._libs.lib.AxisProperty.__set__ (pandas/_libs/lib.c:45255)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 473, in _set_axis
    self._data.set_axis(axis, labels)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pandas/core/internals.py", line 2836, in set_axis
    (old_len, new_len))
ValueError: Length mismatch: Expected axis has 3 elements, new values have 8 elements`

Hello!

I am trying to convert some dictionaries from: [yomichan](https://foosoft.net/projects/yomichan/) and i got the error above.

I skipped the yomichan-import phase since the dictionaries there are already in json format. So i just unzip and then use the command:
`python3 yomi2tab.py -o innocent_corpus.tab yomi_output/`

The dictionaries i want to convert are [innocent_corpus.zip](https://foosoft.net/projects/yomichan/dl/dict/innocent_corpus.zip), [kanjidic_english.zip](https://foosoft.net/projects/yomichan/dl/dict/kanjidic_english.zip), [kireicake.zip](https://foosoft.net/projects/yomichan/dl/dict/kireicake.zip).

Is it because the dictionaries on [yomichan](https://foosoft.net/projects/yomichan/) are not compatible with the script, or is something wrong with my python installation?

Thank you!

**Comment by rtiangha** [comment]
I get the same but I'm on Windows so environment has nothing to do with it. Delete all .json files in the dictionary directory except for the term_bank json files and the script should then run. However, this will only work for the JMdict, JMnedict and Kireicake dictionaries as the others are structured differently. You would need to modify the script to work with the different columns (some dictionaries have less and/or store the information in a different order than the script expects).
